In [1]:
import torch

In [2]:
test_1 = torch.tensor([[1.,2.,3.],[4.,5.,6.]])

print(test_1.shape)
print(test_1.dtype)
print(test_1.ndim)

torch.Size([2, 3])
torch.float32
2


In [3]:
test_2 = torch.randn(2, 5, 100)

print(test_2.shape)
# The dimensions are Documents, Token positions, Vocabs

torch.Size([2, 5, 100])


In [4]:
test_3 = torch.tensor([[[0.2],[0.9],[0.5]]]) 

sum_pooling = test_3.sum(dim=1)
print(sum_pooling)
print(sum_pooling.shape)

max_pooling = test_3.max(dim=1)
print(max_pooling.values)
print(max_pooling.values.shape)

tensor([[1.6000]])
torch.Size([1, 1])
tensor([[0.9000]])
torch.Size([1, 1])


In [5]:
test_4 = torch.randn(2, 5, 100)

sum_pooling = test_4.sum(dim=1)
print(sum_pooling.shape)

max_pooling = test_4.max(dim=1)
print(max_pooling.values.shape)

torch.Size([2, 100])
torch.Size([2, 100])


In [6]:
test_5 = torch.tensor([-1., 0., 2.])

log_p = torch.log1p(torch.relu(test_5))

print(log_p)

tensor([0.0000, 0.0000, 1.0986])


In [7]:
test_6 = torch.ones(2, 5, 100)
mask = torch.tensor([[1,1,1,0,0],[1,1,0,0,0]])

unsqueezed_mask = mask.unsqueeze(-1)

masked = test_6 * unsqueezed_mask
final = masked.sum(dim=1)

print(final)
print(final.shape)

tensor([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
         3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
         3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
         3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
         3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
         3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]])
torch.Size([2, 100])


In [8]:
test_7 = x = torch.tensor([[[-5.],[-2.],[-8.]]])
mask = torch.tensor([[1,1,0]])
unsqueezed_mask = mask.unsqueeze(-1)

masked_A = test_7 * unsqueezed_mask
print("A:", masked_A.max(dim=1).values)

masked_B = test_7.masked_fill(unsqueezed_mask == 0, float('-inf'))
print("B:", masked_B.max(dim=1).values)

A: tensor([[-0.]])
B: tensor([[-2.]])


In [9]:
class TinyModel(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.w = torch.nn.Parameter(torch.tensor(2.0))

    def forward(self, x):
        return (x * self.w).sum()

model = TinyModel()
print(model.w)   

x = torch.tensor([1., 2., 3.])
y = model(x)
print(y)

y.backward()
print(model.w.grad)

Parameter containing:
tensor(2., requires_grad=True)
tensor(12., grad_fn=<SumBackward0>)
tensor(6.)


In [11]:
class NewTinyModel(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x, mask):
        unsqueezed_mask = mask.unsqueeze(-1)

        masked = x * unsqueezed_mask
        final = masked.sum(dim=1)
        return final
    
model = NewTinyModel()

test = torch.ones(2,5,100)
mask = torch.tensor([[1,1,1,0,0],[1,1,0,0,0]])

y = model(test,mask)
print(y.shape)
print(y)

torch.Size([2, 100])
tensor([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
         3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
         3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
         3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
         3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
         3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]])
